name: Build & Deploy Python to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Pull down your code
      - uses: actions/checkout@v4

      # 2) Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3) Install your dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Package into a zip
      - name: Archive application
        run: zip -r app.zip .

      # 5) Push via ZipDeploy
      - name: Deploy to Azure Web App (ZipDeploy)
        uses: azure/webapps-deploy@v2
        with:
          app-name: imageiqblackbox            # <— your Web App’s “Name” from Azure Portal
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip
