name: Build & Deploy Python to Azure WebApp

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the repo
      - uses: actions/checkout@v4

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'           # or any 3.x you need

      # 3) Install your dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) (Optional) Run tests, linting, etc.
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # 5) Zip up the app folder
      - name: Archive application
        run: |
          zip -r app.zip .

      # 6) Deploy to Azure Web App
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}            # your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip
    env:
      AZURE_WEBAPP_NAME: your-app-name
